using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace HetznerCloud.SourceGenerators;

/// <summary>
/// Source generator for high-performance System.Text.Json serialization
/// Generates JsonSerializerContext and custom converters for all Hetzner Cloud models
/// </summary>
[Generator]
public sealed class JsonSerializationGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all model types in HetznerCloud.Models namespace
        var modelTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsModelClass(s),
                transform: static (ctx, _) => GetModelInfo(ctx))
            .Where(static m => m is not null)
            .Collect();

        // Generate JsonSerializerContext
        context.RegisterSourceOutput(modelTypes, GenerateJsonSerializerContext);

        // Generate custom converters for branded IDs
        context.RegisterSourceOutput(modelTypes, GenerateBrandedIdConverters);
    }

    private static bool IsModelClass(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax cds &&
               cds.BaseList?.Types.Any(t => t.Type.ToString().Contains("Record")) == false &&
               cds.Modifiers.Any(m => m.IsKind(SyntaxKind.PublicKeyword));
    }

    private static ModelInfo? GetModelInfo(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        var semanticModel = context.SemanticModel;

        var symbol = semanticModel.GetDeclaredSymbol(classDeclaration);
        if (symbol is not INamedTypeSymbol namedType) return null;

        // Check if in HetznerCloud.Models namespace
        if (namedType.ContainingNamespace?.ToDisplayString() != "HetznerCloud.Models")
            return null;

        // Check if it's a DTO (has JsonPropertyName attributes)
        var hasJsonAttributes = namedType.GetMembers()
            .OfType<IPropertySymbol>()
            .Any(p => p.GetAttributes().Any(a => 
                a.AttributeClass?.Name == "JsonPropertyNameAttribute" ||
                a.AttributeClass?.Name == "JsonConverterAttribute"));

        if (!hasJsonAttributes) return null;

        var properties = namedType.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public)
            .Select(p => new PropertyInfo
            {
                Name = p.Name,
                Type = p.Type.ToDisplayString(),
                JsonPropertyName = p.GetAttributes()
                    .FirstOrDefault(a => a.AttributeClass?.Name == "JsonPropertyNameAttribute")
                    ?.ConstructorArguments.FirstOrDefault().Value?.ToString() ?? p.Name,
                IsNullable = p.NullableAnnotation == NullableAnnotation.Annotated,
                IsCollection = IsCollectionType(p.Type),
                JsonConverter = p.GetAttributes()
                    .FirstOrDefault(a => a.AttributeClass?.Name == "JsonConverterAttribute")
                    ?.ConstructorArguments.FirstOrDefault().Value?.ToString()
            })
            .ToImmutableArray();

        return new ModelInfo
        {
            Name = namedType.Name,
            FullName = namedType.ToDisplayString(),
            Namespace = namedType.ContainingNamespace?.ToDisplayString() ?? "",
            Properties = properties,
            IsRecord = classDeclaration.Modifiers.Any(m => m.IsKind(SyntaxKind.RecordKeyword)),
            IsPartial = classDeclaration.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword))
        };
    }

    private static bool IsCollectionType(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol named)
        {
            return named.IsGenericType && 
                   (named.ConstructedFrom.ToDisplayString() == "System.Collections.Generic.List<T>" ||
                    named.ConstructedFrom.ToDisplayString() == "System.Collections.Generic.IReadOnlyList<T>" ||
                    named.ConstructedFrom.ToDisplayString() == "System.Collections.Generic.IEnumerable<T>" ||
                    named.ConstructedFrom.ToDisplayString() == "System.Collections.Generic.Dictionary<TKey, TValue>" ||
                    named.ConstructedFrom.ToDisplayString() == "System.Collections.Generic.IDictionary<TKey, TValue>");
        }
        return false;
    }

    private static void GenerateJsonSerializerContext(SourceProductionContext context, ImmutableArray<ModelInfo> models)
    {
        var sb = new StringBuilder();
        
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine("using HetznerCloud.Models;");
        sb.AppendLine();
        sb.AppendLine("namespace HetznerCloud.Serialization;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated JsonSerializerContext for Hetzner Cloud models");
        sb.AppendLine("/// Provides AOT-compatible, high-performance serialization");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[JsonSerializable(typeof(object))]");
        
        foreach (var model in models.OrderBy(m => m.Name))
        {
            sb.AppendLine($"[JsonSerializable(typeof({model.FullName}))]");
            if (model.Properties.Any(p => p.IsCollection))
            {
                var collectionTypes = model.Properties
                    .Where(p => p.IsCollection)
                    .Select(p => p.Type)
                    .Distinct();
                foreach (var ct in collectionTypes)
                {
                    sb.AppendLine($"[JsonSerializable(typeof({ct}))]");
                }
            }
        }
        
        sb.AppendLine("internal sealed partial class HetznerCloudJsonContext : JsonSerializerContext");
        sb.AppendLine("{");
        sb.AppendLine("}");

        context.AddSource("HetznerCloudJsonContext.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void GenerateBrandedIdConverters(SourceProductionContext context, ImmutableArray<ModelInfo> models)
    {
        // Generate converters for all branded ID types
        var sb = new StringBuilder();
        
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine("using HetznerCloud.Models;");
        sb.AppendLine();
        sb.AppendLine("namespace HetznerCloud.Serialization;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated JSON converters for strongly-typed branded IDs");
        sb.AppendLine("/// </summary>");
        
        // Find all branded ID types
        var brandedIdTypes = models
            .Where(m => m.Name.EndsWith("Id") && m.Properties.Any(p => p.Name == "Value" && p.Type == "long"))
            .ToList();

        foreach (var model in brandedIdTypes)
        {
            sb.AppendLine($"/// <summary>Converter for {model.Name}</summary>");
            sb.AppendLine($"public sealed class {model.Name}JsonConverter : JsonConverter<{model.FullName}>");
            sb.AppendLine("{");
            sb.AppendLine("    public override void Write(Utf8JsonWriter writer, HetznerCloud.Models.");
            sb.AppendLine($"        {model.Name} value, JsonSerializerOptions options)");
            sb.AppendLine("    {");
            sb.AppendLine("        writer.WriteNumberValue(value.Value);");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine($"    public override {model.FullName} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (reader.TokenType != JsonTokenType.Number)");
            sb.AppendLine("            throw new JsonException($\"Expected number for {model.Name}, got {reader.TokenType}\");");
            sb.AppendLine("        var value = reader.GetInt64();");
            sb.AppendLine("        return new HetznerCloud.Models.");
            sb.AppendLine($"            {model.Name}(value);");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        context.AddSource("BrandedIdConverters.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}

internal sealed record ModelInfo
{
    public required string Name { get; init; }
    public required string FullName { get; init; }
    public required string Namespace { get; init; }
    public required ImmutableArray<PropertyInfo> Properties { get; init; }
    public required bool IsRecord { get; init; }
    public required bool IsPartial { get; init; }
}

internal sealed record PropertyInfo
{
    public required string Name { get; init; }
    public required string Type { get; init; }
    public required string JsonPropertyName { get; init; }
    public required bool IsNullable { get; init; }
    public required bool IsCollection { get; init; }
    public string? JsonConverter { get; init; }
}